[package]
name = "CS-128-Honors-Final-Project"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8"
cbc = "0.1"
rand = "0.8"
base64 = "0.21"
clap = { version = "4.4", features = ["derive"] }
cipher = "0.4"