[package]
name = "CS-128-Honors-Final-Project"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8"
block-modes = "0.8" # We didn't use 0.9 because it doesn't export Cbc directly
block-padding = "0.3"
rand = "0.8"
base64 = "0.21"